### ISSUE TITLE
Queue list empty

### ISSUE THREAD

**Issue by AaronConnell** [DouglasCAyers/sfdc-remedyforce-queue-assignments#1]
I deployed this to my sandbox and when I access the Queue Member Assignment page there are no queues listed in the picklist.

Looking at the debug logs, there are no errors reported when I load this page.

I do have several queues, and have access to all the pages/classes.

Any thoughts on why there are no queues listed to select?

![screen shot 2015-04-28 at 11 16 24 am](https://cloud.githubusercontent.com/assets/12157270/7375763/0af79646-ed98-11e4-927b-71e51959dfff.png)

**Comment by douglascayers** [comment]
Hi Aaron!

Yes, the controller is currently filtering by queues whose Developer Name (API Name) starts with `BMCRF_`. That was a naming convention I was using in this org as this page was used exclusively to manage queue members for Remedyforce and not just "all" queues in our environment.

You want to modify line 175, or the entire `WHERE` clause of the SOQL query of the `BMCRFQueueMemberAssignmentController` to meet your needs and/or prefix your Developer Names of your Remedyforce queues with `BMCRF_`.

I admit, this wasn't the most generic example of the concept and still has some nuances of my particular use case involved.

**Comment by AaronConnell** [comment]
Awesome - thanks for the quick reply! All fixed up now.
